### ISSUE TITLE
Historical data missing properties

### ISSUE THREAD

**Issue by dereklieu** [anandthakker/us-atlas#17]
Noticed during spot check: following states have their county `reportingUnitName` listed as `null`:

CT
MA
ME
NH
RI
VT

Since these don't have values, they are blanks in the current historical map. Need to get Dan to correct this data, I'll include it along with the delivery note on Monday.

cc @mileswwatkins

**Comment by mileswwatkins** [comment]
@dereklieu, can you give me a `raceUID` where this happens? Having trouble finding it; for example, `2012-11-06-MA-P` looks fine to me, for example, and searching for `"reportingunitName":null` or `"reportingunitName":""` or `"reportingunitName":"null"` turns up no results.

**Comment by dereklieu** [comment]
2012-11-06-NH-P
2012-11-06-ME-P
2012-11-06-VT-P

etc. for the states I listed above.

**Comment by mileswwatkins** [comment]
Huh, I'm seeing a non-null value, in my copy of `historical.json` downloaded from S3 at 11 AM today. For example, the first RU in `2012-11-06-ME-P`:

```
{"electionDate":"2012-11-06","statePostal":"ME","timestamp":"2012-11-20T13:16:53.00Z","raceUID":"2012-11-06-ME-P","raceType":"General","raceTypeID":"G","officeID":"P","officeName":"President",
"national": true,
"reportingUnits":[
{"reportingUnitUID":"2012-11-06-ME-FIPSCode-23001","level":"FIPSCode","reportingunitName":"Androscoggin",
"fipsCode":"23001",
"candidates":[
{"candidateUID":"1918","party":"Dem",
"incumbent":true,
"winner":"X",
"first":"Barack",
"last":"Obama",
"fullname":"Barack Obama","ballotOrder":1,"voteCount":28912},
{"candidateUID":"893","party":"GOP",
"first":"Mitt",
"last":"Romney",
"fullname":"Mitt Romney","ballotOrder":2,"voteCount":22210},
{"candidateUID":"31708","party":"Lib",
"first":"Gary",
"last":"Johnson",
"fullname":"Gary Johnson","ballotOrder":3,"voteCount":837},
{"candidateUID":"895","party":"Grn",
"first":"Jill",
"last":"Stein",
"fullname":"Jill Stein","ballotOrder":4,"voteCount":580}]}
```

Are you possibly looking for `reportingUnitName` instead of `reportingunitName` (which is the AP's capitalization)?

**Comment by dereklieu** [comment]
Oh interesting, we could just have an old version of the data file checked into the repo.

Does Dan let you know when he makes tweaks to the files?

**Comment by mileswwatkins** [comment]
He does sometimes? But I think we should work under the assumption that Dan or someone else on WaPo can make silent updates to `historical.json` and `expectations.json`. (Or maybe add a breaking error during the build process if the last-updated time of the S3 file is newer than expected?)

**Comment by dereklieu** [comment]
The problem is, rolling map tiles for historical data isn't automated (as in, there's no worker making new tiles every time we deploy a new version of `wapo-components`). So he can make silent updates for a few more days, but past the end of this week or whenever Wapo publishes preview maps, he needs to tell us because nothing live is pointed at the S3 bucket, not even the front end, where a script simplifies the file to get file sizes down before serving it.

**Comment by dereklieu** [comment]
Generating new tiles is also pretty distracting and, without knowing what was touched, requires us to do some checks of the data which can make the whole thing take over an hour. I would say he needs to be super clear 1. when he changes something, 2. what he changed.

**Comment by mileswwatkins** [comment]
The current version lacks this ticket's problem.
